<a href="https://colab.research.google.com/github/fabiankmroh/aistudy/blob/master/dropout_mini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
from torch import nn

In [3]:
x = torch.randn(100, 3)
layer = nn.Linear(3, 5)

print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[ 0.3170,  0.1597, -0.4432],
        [ 0.2833, -0.4098,  0.4139],
        [-0.0993,  0.0991, -0.4223],
        [ 0.5323,  0.3571, -0.0607],
        [ 0.0933, -0.2667, -0.4012]], requires_grad=True)
Parameter containing:
tensor([ 0.0271,  0.4079,  0.4207, -0.4942,  0.1318], requires_grad=True)


In [4]:
x = torch.randn(2, 5)
layer = nn.ReLU()

print(x)
print(layer(x))

tensor([[ 1.2597,  1.4936, -0.8143, -1.3607, -0.0032],
        [ 0.2958, -0.4983,  0.6373, -0.3321,  0.9733]])
tensor([[1.2597, 1.4936, 0.0000, 0.0000, 0.0000],
        [0.2958, 0.0000, 0.6373, 0.0000, 0.9733]])


In [5]:
layer = nn.BatchNorm1d(3)
print(layer.weight)
print(layer.bias)

x = torch.randn(5,3)
print(x)
print(layer(x))

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
tensor([[-1.6281, -1.0657, -0.9312],
        [ 1.4869, -0.4773, -0.6497],
        [-0.4895, -0.4202, -0.5762],
        [ 1.7189, -0.2716, -1.6326],
        [-1.6394,  0.6803,  0.7555]])
tensor([[-1.0384, -1.3371, -0.4176],
        [ 1.0927, -0.2947, -0.0551],
        [-0.2595, -0.1937,  0.0394],
        [ 1.2514,  0.0696, -1.3207],
        [-1.0462,  1.7558,  1.7540]], grad_fn=<NativeBatchNormBackward0>)


In [6]:
layer = nn.BatchNorm2d(3)
print(layer.weight)
print(layer.bias)

x = torch.randn(5,3,32,32)
print(layer(x).shape)

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
torch.Size([5, 3, 32, 32])


In [7]:
x = torch.randn(3, 7)
drop = nn.Dropout(p = 0.1)
print(x)
print(drop(x) * (1 - 0.3))

drop.eval()
print(drop(x))

tensor([[ 2.2095, -1.2030,  0.6286, -0.6254, -0.0502, -1.2173,  0.0558],
        [ 0.0444,  0.4272,  1.8413,  1.0508, -0.1476, -1.7869,  0.3268],
        [-1.3983,  1.1109, -0.9205,  0.2659, -0.3017,  0.9022, -1.9408]])
tensor([[ 1.7185, -0.9357,  0.4889, -0.4865, -0.0391, -0.9468,  0.0434],
        [ 0.0345,  0.3323,  1.4321,  0.8173, -0.1148, -1.3898,  0.2542],
        [-1.0875,  0.8640, -0.7160,  0.2068, -0.2346,  0.7017, -1.5095]])
tensor([[ 2.2095, -1.2030,  0.6286, -0.6254, -0.0502, -1.2173,  0.0558],
        [ 0.0444,  0.4272,  1.8413,  1.0508, -0.1476, -1.7869,  0.3268],
        [-1.3983,  1.1109, -0.9205,  0.2659, -0.3017,  0.9022, -1.9408]])


In [8]:
class sample_model(nn.Module):
  def __init__(self):
    super().__init__()
    self.drop_layer = nn.Sequential(
        nn.Linear(5, 7),
        nn.ReLU(),
        nn.Dropout(p = 0.3)
    )

  def forward(self, x):
    x = self.drop_layer(x)
    return x

In [9]:
model = sample_model()
model.train()

sample_model(
  (drop_layer): Sequential(
    (0): Linear(in_features=5, out_features=7, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.3, inplace=False)
  )
)

In [10]:
x = torch.randn(3,5)
print(model(x))

tensor([[0.0000, 0.0000, 1.2547, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.4585, 0.2899, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0646, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)


In [11]:
model.eval()
print(model(x))

tensor([[0.0000, 0.0000, 0.8783, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0857, 0.3210, 0.2030, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.9870, 0.0000, 0.0452, 0.0000, 0.0000]],
       grad_fn=<ReluBackward0>)
